"""Regenerate packaging/THIRD_PARTY_NOTICES.txt from the packaging venv's
installed dependencies.

Run with the venv's own Python so it can see PySide6, numpy, etc.:
    %LOCALAPPDATA%\\EtalumaVP-dev\\v0.9\\.venv\\Scripts\\python.exe packaging\\prepare_assets.py
packaging\\build.ps1 runs this automatically before the PyInstaller step.
Stdlib only, by design (task requirement: a pip-licenses-like scan
implemented in plain Python with no extra dependencies).

Adapted from history/04_2026-09_codex_v0.3/packaging/prepare_assets.py.
Differences from 0.3:
  - No icon generation. V04 already ships a real
    source/etaluma_video/assets/icon.ico and icon.png (owned by other
    agents per docs/CONTRACTS.md); this script never touches them.
  - Broader license-file matching. 0.3's filter — file name ends with
    ".txt", ".md", "LICENSE" or "COPYING" — silently dropped every one of
    imagecodecs' ~30 vendored `LICENSE-<library>` files (e.g.
    "LICENSE-aom": ends with "aom", not "LICENSE") and would also miss a
    plain "COPYING.LESSER" or "LICENSE.rst". This version matches by
    keyword anywhere in the filename instead of by suffix.
  - Guards distributions with missing/partial metadata instead of assuming
    dist.metadata and dist.files are always populated.
  - Caps any single bundled license file at ~1 MB so one oversized vendored
    document cannot dominate the output.
  - No WebView2 (0.4 has none); the fixed closing paragraphs describe the
    files v0.4 actually bundles (Qt6*.dll, the imageio-ffmpeg ffmpeg exe).
"""
from __future__ import annotations

import importlib.metadata as metadata
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # Timelapse video processing software v0.9
PACKAGING_DIR = ROOT / "packaging"
OUTPUT = PACKAGING_DIR / "THIRD_PARTY_NOTICES.txt"

MAX_FILE_BYTES = 1_000_000  # skip pathologically large bundled license files
LICENSE_KEYWORDS = ("license", "licence", "copying", "notice", "authors")


def _is_license_like(filename: str) -> bool:
    lower = filename.lower()
    return any(keyword in lower for keyword in LICENSE_KEYWORDS)


def _read_capped(path: Path) -> str | None:
    try:
        size = path.stat().st_size
    except OSError:
        return None
    if size > MAX_FILE_BYTES:
        return f"[skipped: {size:,} bytes, over the {MAX_FILE_BYTES:,} byte cap]"
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _distribution_section(dist: metadata.Distribution, seen_files: set[str]) -> list[str]:
    if dist.metadata is None:
        return []
    name = dist.metadata.get("Name")
    if not name:
        return []
    version = dist.version or ""
    license_field = (
        dist.metadata.get("License-Expression")
        or dist.metadata.get("License")
        or "See package notices below"
    )

    lines = ["", "=" * 72, f"{name} {version}", f"License: {license_field}"]

    for entry in dist.files or ():
        if not _is_license_like(entry.name):
            continue
        located = dist.locate_file(entry)
        candidate = Path(located)
        key = str(candidate)
        if key in seen_files:
            continue
        if not candidate.exists():
            continue
        seen_files.add(key)
        text = _read_capped(candidate)
        if text is None:
            continue
        lines.append("")
        lines.append(f"--- {entry} ---")
        lines.append(text)

    return lines


def collect_notices() -> list[str]:
    lines = [
        "TIMELAPSE VIDEO PROCESSING — THIRD-PARTY NOTICES",
        "",
        "This file lists the license of every package installed in the",
        "packaging environment used to build this release, generated by",
        "packaging/prepare_assets.py. It is bundled into the frozen app",
        "(see packaging/app.spec) and installed under the program's",
        "_internal\\ folder.",
        "",
        f"Python: {sys.version}",
    ]

    seen_files: set[str] = set()
    dists = sorted(
        metadata.distributions(),
        key=lambda d: ((d.metadata.get("Name") if d.metadata else None) or "").lower(),
    )
    for dist in dists:
        lines.extend(_distribution_section(dist, seen_files))

    lines.append("")
    lines.append("=" * 72)
    lines.append("Qt / PySide6")
    lines.append(
        "PySide6 is licensed under the LGPL-3.0 (commercial Qt licensing is\n"
        "also available from The Qt Company; this build uses the open-source\n"
        "LGPL terms). The Qt shared libraries (Qt6*.dll) are bundled as\n"
        "separate, replaceable files under the installed program's\n"
        "_internal\\ folder, not statically linked into\n"
        "\"Timelapse Video Processing.exe\" — which satisfies the LGPL's\n"
        "relinking requirement. Full license text:\n"
        "https://www.gnu.org/licenses/lgpl-3.0.txt\n"
        "Qt licensing overview: https://www.qt.io/licensing/"
    )

    lines.append("")
    lines.append("=" * 72)
    lines.extend(_ffmpeg_section("\n".join(lines)))

    python_license = Path(sys.base_prefix) / "LICENSE.txt"
    if python_license.exists():
        text = _read_capped(python_license)
        if text:
            lines.append("")
            lines.append("=" * 72)
            lines.append("Python")
            lines.append(text)

    return lines


def _gpl3_text(collected: str) -> str:
    """The GNU GPL v3 text as another bundled package already ships it, or ''."""
    match = re.search(r"[ \t]*GNU GENERAL PUBLIC LICENSE\s*\n\s*Version 3, 29 June 2007", collected)
    if not match:
        return ""
    end = collected.find("END OF TERMS AND CONDITIONS", match.start())
    return collected[match.start():end + len("END OF TERMS AND CONDITIONS")] if end > 0 else ""


def _ffmpeg_section(collected: str) -> list[str]:
    """The bundled ffmpeg.exe: its version, its licence (a GPL-3.0 build) and where its source is (0.8)."""
    exe, output = None, ""
    try:
        import imageio_ffmpeg  # noqa: WPS433

        exe = Path(imageio_ffmpeg.get_ffmpeg_exe())
        output = subprocess.run([str(exe), "-hide_banner", "-version"], capture_output=True, text=True,
                                timeout=60).stdout
    except Exception as exc:  # the notice still says what is bundled
        print(f"warning: ffmpeg -version failed: {exc}")
    first = output.splitlines()[0] if output else "ffmpeg (version not read)"
    config = next((line for line in output.splitlines() if line.startswith("configuration:")), "")
    gpl3 = "--enable-gpl" in config and "--enable-version3" in config
    match = re.search(r"ffmpeg version (\d+(?:\.\d+)*)", first)
    version = match.group(1) if match else ""
    source = f"https://ffmpeg.org/releases/ffmpeg-{version}.tar.xz" if version else "https://ffmpeg.org/download.html"
    section = [
        f"FFmpeg {version}".strip(),
        "License: GPL-3.0-or-later" if gpl3 else "License: GPL or LGPL, see the build configuration below",
        "",
        f"Bundled as _internal\\imageio_ffmpeg\\binaries\\{exe.name if exe else 'ffmpeg.exe'} ({first}).",
        "It is a separate program that Timelapse Video Processing runs to encode the MP4 (H.264)",
        "videos. It is not linked into the app, whose own code stays under the MIT licence. This",
        "FFmpeg build is licensed under the GNU General Public License, version 3 or later (it was",
        "built with --enable-gpl --enable-version3 and includes x264 and x265).",
        "",
        "Build configuration: " + (config.partition(":")[2].strip() or "not read"),
        "",
        "Corresponding source code:",
        f"  FFmpeg {version}: {source}",
        "  This build and the source of every library it includes: https://www.gyan.dev/ffmpeg/builds/",
        "  imageio-ffmpeg, which ships the binary: https://github.com/imageio/imageio-ffmpeg",
        "On request through the project's Issues page, the maintainers provide a copy of this",
        "corresponding source code for at least three years after the release that contains it.",
        "",
    ]
    gpl = _gpl3_text(collected)
    section.append(gpl if gpl else "GNU General Public License, version 3: https://www.gnu.org/licenses/gpl-3.0.txt")
    return section


def main() -> int:
    PACKAGING_DIR.mkdir(exist_ok=True)
    notices = collect_notices()
    OUTPUT.write_text("\n".join(notices), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
